name: Automatisation Mayah Store

on:
  schedule:
    - cron: '0 * * * *' # S'exécute automatiquement toutes les 6 heures
  workflow_dispatch: # Permet de lancer le script manuellement depuis GitHub

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-aliexpress-api
        
      - name: Run python script
        run: python update_stock.py
        env:
          ALIEXPRESS_APP_KEY: ${{ secrets.ALIEXPRESS_APP_KEY }}
          ALIEXPRESS_APP_SECRET: ${{ secrets.ALIEXPRESS_APP_SECRET }}
